insert into BILLING_LOG_HIS        select * from BILLING_LOG         where trunc(deal_end_date)<trunc(sysdate)-90;
delete from BILLING_LOG        where trunc(deal_end_date)<trunc(sysdate)-90;
commit;
insert into ERR_TICKET_HIS         select * from ERR_TICKET          where trunc(deal_date)<trunc(sysdate)-90;
delete from ERR_TICKET          where trunc(deal_date)<trunc(sysdate)-90;
commit;
insert into INSERT_LOG_HIS         select * from INSERT_LOG          where trunc(deal_end_date)<trunc(sysdate)-90;
delete from INSERT_LOG        where trunc(deal_end_date)<trunc(sysdate)-90;
commit;
insert into PICK_LOG_HIS           select * from PICK_LOG            where trunc(deal_end_date)<trunc(sysdate)-90;
delete from PICK_LOG          where trunc(deal_end_date)<trunc(sysdate)-90;
commit;
insert into PREP_LOG_HIS           select * from PREP_LOG            where trunc(deal_end_date)<trunc(sysdate)-90;
delete from PREP_LOG            where trunc(deal_end_date)<trunc(sysdate)-90;
commit;
insert into STAT_LOG_HIS           select * from STAT_LOG            where trunc(deal_end_date)<trunc(sysdate)-90;
delete from STAT_LOG           where trunc(deal_end_date)<trunc(sysdate)-90;
commit;
insert into UPDATA_LOG_HIS         select * from UPDATA_LOG          where trunc(deal_end_date)<trunc(sysdate)-90;
delete from UPDATA_LOG          where trunc(deal_end_date)<trunc(sysdate)-90;
commit;
insert into UPDATA_PROC_LOG_HIS    select * from UPDATA_PROC_LOG     where trunc(file_date)<trunc(sysdate)-90;
delete from UPDATA_PROC_LOG    where trunc(file_date)<trunc(sysdate)-90;
commit;
